tasks:
  - before: |
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get update
      sudo apt-get install -q -y libunwind-dev build-essential clang libssl-dev pkg-config
      DFX_VERSION=0.24.2 DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      source "$HOME/.local/share/dfx/env"
      open README.md

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Dfx
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Vite
    port: 5173
    visibility: public
    onOpen: open-browser
